// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wfzgvuscivyzwuoaumto.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Indmemd2dXNjaXZ5end1b2F1bXRvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM5NzAwMTcsImV4cCI6MjA2OTU0NjAxN30.cXn3ddJjftV-RUpSKV0SM1TOgMQhKzsXQ0d0W7481Bs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});